color0       #404348
color8       #98A9A7
color1       #619CD0
color9       #619CD0
color2       #18ABBA
color10      #18ABBA
color3       #07B180
color11      #07B180
color4       #B1BBA6
color12      #B1BBA6
color5       #A6D6F4
color13      #A6D6F4
color6       #C3F6EE
color14      #C3F6EE
color7       #D9F2EE
color15      #D9F2EE