# ~/.config/hypr/hyprlauncher.conf

general {
    grab_focus = true      # Focus the launcher window immediately
}

finders {
    default_finder = desktop # Starts with the desktop application search
    desktop_prefix = "󰍉  "
    desktop_icons = true     # Shows icons for applications
    math_prefix = "="        # Type '=' to start the calculator module
}

ui {
    window_size = 600 400    # Set the launcher dimensions
}

cache {
    enabled = true           # Cache frequently used apps for faster access
}
