[preferred]
# Use the hyprland portal for screen sharing and windows
default=hyprland
# Use the GTK portal for file pickers and dark/light mode detection
org.freedesktop.impl.portal.FileDialog=gtk
org.freedesktop.impl.portal.Settings=gtk
